### ISSUE TITLE
`colons` and `slashes` could be `Applicative f => IndexedLensLike' Int f Text Text`

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [bellroy/aws-arn#9]
This is inspired by the type of `worded` and `lined` in `lens`: `worded, lined :: Applicative f => IndexedLensLike' Int f String String`

**Comment by cdaloisio** [comment]
@JackKelly-Bellroy is this something that we still would like to implement?

**Comment by JackKelly-Bellroy** [comment]
No, because we no longer commit to any particular lens library, and we lose the ability to replace parts (like we need to do in Lambda Authorisers).
